### ISSUE TITLE
Modification Station recipes don't trigger the Plasteel Ingot recipe

### ISSUE THREAD

**Issue by kynoch** [tinyhoot/Deathrun-Remade#11]
Once you build a modification station you receive the recipe for lightweight high capacity tank, which requires a plasteel ingot to craft it. I didn't receive the plasteel ingot recipe until I scanned the multipurpose room (and received the recipe for the large room)

**Comment by tinyhoot** [comment]
The plasteel ingot unlocks upon building any vehicle or scanning either a multipurpose room or observatory. This is vanilla behaviour and intended as far as the mod is concerned.
