### ISSUE TITLE
Lifepod always sinks, regardless of setting.

### ISSUE THREAD

**Issue by RHubl** [tinyhoot/Deathrun-Remade#13]
Due to a bug (from Subnautica itself, rather than mods, it appears), the beacon for the Lifepod randomly disappear at times and isn't able to be manually reset via the PDA. As such, I turned off the "Lifepod sinks" setting in the mod options. I confirmed this was switched off in the config files (Boolean = false).

However, the Lifepod will still always sink, regardless of settings. Looking over the patch notes of 1.03, perhaps the fix to the Lifepod sometimes not sinking has caused this. 

Will investigate whether the bug still occurs in 1.02 and report back.

**Comment by RHubl** [comment]
Also occurs in 1.02

**Comment by RayRobertson72** [comment]
I’ve working as Mod Support in the Subnautica Modding Discord server for 16 months now and I’ve never heard anyone mentioning the Lifepod beacon disappearing. I also have just over 1k hours in the game and have never experienced it either.

**Comment by RHubl** [comment]
> I’ve working as Mod Support in the Subnautica Modding Discord server for 16 months now and I’ve never heard anyone mentioning the Lifepod beacon disappearing. I also have just over 1k hours in the game and have never experienced it either.

A quick google shows that it isn't an issue exclusive to myself (there are posts about it regarding Switch and PS versions too). Maybe it's just very uncommon.

Anyway, that is besides the point and the issue is that the Lifepod always sinks, even when it is instructed not to in the settings.
