### ISSUE TITLE
Radiation visual effects visible after reactor repair

### ISSUE THREAD

**Issue by tinyhoot** [tinyhoot/Deathrun-Remade#6]
It seems that, on the highest setting, the visual effects of radiation continue even after the reactor has been repaired. It's spotty and does not happen everywhere; supposedly the locker room works as intended but areas near it do not.

**Comment by Mar-Veloz** [comment]
I also experienced this on the "Reminder" radiation setting, so I don't think the bug is unique to the "Chernobyl" setting. I was able to fix the bug for myself locally with a one-line change, which I'll submit it as a PR.
